// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define Data2RVizCompdef_Data2RViz_impl_BODY

/************************************************************
 Data2RViz_impl class body
 ************************************************************/

// include associated header file
#include "Data2RVizCompdef/Data2RViz_impl.h"

// Derived includes directives
#include "rclcpp/rclcpp.hpp"

namespace Data2RVizCompdef {

// static attributes (if any)

/**
 * 
 * @param options 
 */
Data2RViz_impl::Data2RViz_impl(rclcpp::NodeOptions /*in*/options) :
		Data2RViz(options) {
}

/**
 * 
 * @param image 
 * @param float32multiarray 
 * @param string 
 */
void Data2RViz_impl::commandsHandler(
		const sensor_msgs::msg::Image::SharedPtr /*in*/image,
		const std_msgs::msg::Float32MultiArray::SharedPtr /*in*/float32multiarray,
		const std_msgs::msg::String::SharedPtr /*in*/string) {
}

/**
 * 
 */
void Data2RViz_impl::imageHandler() {
}

/**
 * 
 */
void Data2RViz_impl::pointsHandler() {
}

} // of namespace Data2RVizCompdef

/************************************************************
 End of Data2RViz_impl class body
 ************************************************************/
