// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef DATA2RVIZCOMPDEF_DATA2RVIZ_IMPL_H
#define DATA2RVIZCOMPDEF_DATA2RVIZ_IMPL_H

/************************************************************
 Data2RViz_impl class header
 ************************************************************/

#include "Data2RVizCompdef/Pkg_Data2RVizCompdef.h"

#include "Data2RVizCompdef/Data2RViz.h"
#include "sensor_msgs/msg/image.hpp"
#include "std_msgs/msg/float32multi_array.hpp"
#include "std_msgs/msg/string.hpp"

namespace ros2Library {
namespace rclcpp {
class NodeOptions;
}
}

namespace Data2RVizCompdef {

/************************************************************/
/**
 * This is a skeleton class generated for component Data2RViz
 * Copy it into the source folder as an initial base (or copy parts
 * of it whenever you add modify the component).
 * 
 */
class Data2RViz_impl: public Data2RViz {
public:

	/**
	 * 
	 * @param options 
	 */
	Data2RViz_impl(rclcpp::NodeOptions /*in*/options);

	/**
	 * 
	 * @param image 
	 * @param float32multiarray 
	 * @param string 
	 */
	void commandsHandler(const sensor_msgs::msg::Image::SharedPtr /*in*/image,
			const std_msgs::msg::Float32MultiArray::SharedPtr /*in*/float32multiarray,
			const std_msgs::msg::String::SharedPtr /*in*/string);

	/**
	 * 
	 */
	void imageHandler();

	/**
	 * 
	 */
	void pointsHandler();

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Data2RVizCompdef

/************************************************************
 End of Data2RViz_impl class header
 ************************************************************/

#endif
