// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define HandTrackerCompdef_HandTracker_impl_BODY

/************************************************************
 HandTracker_impl class body
 ************************************************************/

// include associated header file
#include "HandTrackerCompdef/HandTracker_impl.h"

// Derived includes directives
#include "rclcpp/rclcpp.hpp"

namespace HandTrackerCompdef {

// static attributes (if any)

/**
 * 
 * @param options 
 */
HandTracker_impl::HandTracker_impl(rclcpp::NodeOptions /*in*/options) :
		HandTracker(options) {
}

/**
 * 
 * @param image 
 */
void HandTracker_impl::imageHandler(
		const sensor_msgs::msg::Image::SharedPtr /*in*/image) {
}

} // of namespace HandTrackerCompdef

/************************************************************
 End of HandTracker_impl class body
 ************************************************************/
