// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef HANDTRACKERCOMPDEF_HANDTRACKER_IMPL_H
#define HANDTRACKERCOMPDEF_HANDTRACKER_IMPL_H

/************************************************************
 HandTracker_impl class header
 ************************************************************/

#include "HandTrackerCompdef/Pkg_HandTrackerCompdef.h"

#include "HandTrackerCompdef/HandTracker.h"
#include "sensor_msgs/msg/image.hpp"

namespace ros2Library {
namespace rclcpp {
class NodeOptions;
}
}

namespace HandTrackerCompdef {

/************************************************************/
/**
 * This is a skeleton class generated for component HandTracker
 * Copy it into the source folder as an initial base (or copy parts
 * of it whenever you add modify the component).
 * 
 */
class HandTracker_impl: public HandTracker {
public:

	/**
	 * 
	 * @param options 
	 */
	HandTracker_impl(rclcpp::NodeOptions /*in*/options);

	/**
	 * 
	 * @param image 
	 */
	void imageHandler(const sensor_msgs::msg::Image::SharedPtr /*in*/image);

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace HandTrackerCompdef

/************************************************************
 End of HandTracker_impl class header
 ************************************************************/

#endif
