// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define GestureDetectorCompdef_GestureDetector_impl_BODY

/************************************************************
 GestureDetector_impl class body
 ************************************************************/

// include associated header file
#include "GestureDetectorCompdef/GestureDetector_impl.h"

// Derived includes directives
#include "rclcpp/rclcpp.hpp"

namespace GestureDetectorCompdef {

// static attributes (if any)

/**
 * 
 * @param options 
 */
GestureDetector_impl::GestureDetector_impl(rclcpp::NodeOptions /*in*/options) :
		GestureDetector(options) {
}

/**
 * 
 * @param float32multiarray 
 */
void GestureDetector_impl::fNewFunction(
		const std_msgs::msg::Float32MultiArray::SharedPtr /*in*/float32multiarray) {
}

} // of namespace GestureDetectorCompdef

/************************************************************
 End of GestureDetector_impl class body
 ************************************************************/
