// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef GESTUREDETECTORCOMPDEF_GESTUREDETECTOR_IMPL_H
#define GESTUREDETECTORCOMPDEF_GESTUREDETECTOR_IMPL_H

/************************************************************
 GestureDetector_impl class header
 ************************************************************/

#include "GestureDetectorCompdef/Pkg_GestureDetectorCompdef.h"

#include "GestureDetectorCompdef/GestureDetector.h"
#include "std_msgs/msg/float32multi_array.hpp"

namespace ros2Library {
namespace rclcpp {
class NodeOptions;
}
}

namespace GestureDetectorCompdef {

/************************************************************/
/**
 * This is a skeleton class generated for component GestureDetector
 * Copy it into the source folder as an initial base (or copy parts
 * of it whenever you add modify the component).
 * 
 */
class GestureDetector_impl: public GestureDetector {
public:

	/**
	 * 
	 * @param options 
	 */
	GestureDetector_impl(rclcpp::NodeOptions /*in*/options);

	/**
	 * 
	 * @param float32multiarray 
	 */
	void fNewFunction(
			const std_msgs::msg::Float32MultiArray::SharedPtr /*in*/float32multiarray);

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace GestureDetectorCompdef

/************************************************************
 End of GestureDetector_impl class header
 ************************************************************/

#endif
