// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef DATA2RVIZCOMPDEF_DATA2RVIZ_H
#define DATA2RVIZCOMPDEF_DATA2RVIZ_H

/************************************************************
 Data2RViz class header
 ************************************************************/

#include "Data2RVizCompdef/Pkg_Data2RVizCompdef.h"

#include "rclcpp_lifecycle/lifecycle_node.hpp"
#include "sensor_msgs/msg/image.hpp"
#include "std_msgs/msg/float32multi_array.hpp"
#include "std_msgs/msg/string.hpp"

// Include from Include stereotype (header)
#include <rclcpp/rclcpp.hpp>

// End of Include stereotype (header)

namespace ros2Library {
namespace rclcpp {
class NodeOptions;
}
}
namespace ros2Library {
namespace rclcpp {
class Subscription;
}
}

namespace Data2RVizCompdef {

/************************************************************/
/**
 * 
 */
class Data2RViz: public rclcpp_lifecycle::LifecycleNode {
public:

	/**
	 * 
	 */
	rclcpp::Subscription<sensor_msgs::msg::Image>::SharedPtr image_S_sub_;

	/**
	 * 
	 */
	rclcpp::Subscription<std_msgs::msg::Float32MultiArray>::SharedPtr points_S_sub_;

	/**
	 * 
	 */
	rclcpp::Subscription<std_msgs::msg::String>::SharedPtr command_S_sub_;

	/**
	 * 
	 * @param options 
	 */
	Data2RViz(rclcpp::NodeOptions /*in*/options);

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Data2RVizCompdef

/************************************************************
 End of Data2RViz class header
 ************************************************************/

#endif
